#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"
echo "### sketch_1_5_streamgraph ###"
bash "run_sketch_1_5_streamgraph.sh"
echo "### sketch_1_2_leaderboard ###"
bash "run_sketch_1_2_leaderboard.sh"
echo "### sketch_1_13_compare ###"
bash "run_sketch_1_13_compare.sh"
echo "### sketch_2_4_map ###"
bash "run_sketch_2_4_map.sh"
echo "### sketch_2_2_heatmap ###"
bash "run_sketch_2_2_heatmap.sh"
echo "### sketch_2_6_small_multiples ###"
bash "run_sketch_2_6_small_multiples.sh"
echo "### sketch_3_5_scatter ###"
bash "run_sketch_3_5_scatter.sh"
echo "### sketch_3_2_violin ###"
bash "run_sketch_3_2_violin.sh"
echo "### sketch_3_3_positional ###"
bash "run_sketch_3_3_positional.sh"
echo
echo "[OK] all 9 sketches ran cleanly."
